var PRESET_MANAGER;
var ONLINE_STORE;
var LOCAL_STORE;
var MAX_BANK_PRESETS = 128;
var N_BYTES_PER_BANK = 98;

var CONTROLS_STRUCTURE = [
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 67, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 68, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 69, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 70, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 71, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 81, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 82, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 83, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 84, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 85, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 86, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 87, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 88, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 89, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 90, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 91, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 92, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 93, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 94, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 95, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 96, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": null, 
        "name": "", 
        "layoutRow": null, 
        "color": "", 
        "section": "", 
        "displayValueFuncName": "", 
        "type": "", 
        "byte": 97, 
        "channel": null, 
        "layoutCol": null
    }, 
    {
        "midi": 40, 
        "name": "SPEED", 
        "layoutRow": 1, 
        "color": "white", 
        "section": "VCO", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 0, 
        "channel": 1, 
        "layoutCol": 1
    }, 
    {
        "midi": 41, 
        "name": "PWM", 
        "layoutRow": 1, 
        "color": "green", 
        "section": "VCO", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 1, 
        "channel": 1, 
        "layoutCol": 2
    }, 
    {
        "midi": 42, 
        "name": "PW", 
        "layoutRow": 1, 
        "color": "green", 
        "section": "VCO", 
        "displayValueFuncName": "rangePW", 
        "type": "slider", 
        "byte": 2, 
        "channel": 1, 
        "layoutCol": 3
    }, 
    {
        "midi": 43, 
        "name": "SQUARE ON", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCO", 
        "displayValueFuncName": "rangeOnOff", 
        "type": "switchOffOn", 
        "byte": 73, 
        "channel": 1, 
        "layoutCol": 4
    }, 
    {
        "midi": 44, 
        "name": "SAW ON", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCO", 
        "displayValueFuncName": "rangeOnOff", 
        "type": "switchOffOn", 
        "byte": 74, 
        "channel": 1, 
        "layoutCol": 5
    }, 
    {
        "midi": 45, 
        "name": "NOISE", 
        "layoutRow": 1, 
        "color": "gray", 
        "section": "VCO", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 3, 
        "channel": 1, 
        "layoutCol": 6
    }, 
    {
        "midi": 46, 
        "name": "HPF", 
        "layoutRow": 1, 
        "color": "green", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 4, 
        "channel": 1, 
        "layoutCol": 7
    }, 
    {
        "midi": 47, 
        "name": "RESh", 
        "layoutRow": 1, 
        "color": "red", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 5, 
        "channel": 1, 
        "layoutCol": 8
    }, 
    {
        "midi": 48, 
        "name": "LPF", 
        "layoutRow": 1, 
        "color": "green", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 6, 
        "channel": 1, 
        "layoutCol": 9
    }, 
    {
        "midi": 49, 
        "name": "RESl", 
        "layoutRow": 1, 
        "color": "red", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 7, 
        "channel": 1, 
        "layoutCol": 10
    }, 
    {
        "midi": 50, 
        "name": "IL", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeIL", 
        "type": "slider", 
        "byte": 8, 
        "channel": 1, 
        "layoutCol": 11
    }, 
    {
        "midi": 51, 
        "name": "AL", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeAL", 
        "type": "slider", 
        "byte": 9, 
        "channel": 1, 
        "layoutCol": 12
    }, 
    {
        "midi": 52, 
        "name": "A", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 10, 
        "channel": 1, 
        "layoutCol": 13
    }, 
    {
        "midi": 53, 
        "name": "D", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 11, 
        "channel": 1, 
        "layoutCol": 14
    }, 
    {
        "midi": 54, 
        "name": "R", 
        "layoutRow": 1, 
        "color": "yellow", 
        "section": "VCF", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 12, 
        "channel": 1, 
        "layoutCol": 15
    }, 
    {
        "midi": 55, 
        "name": "VCF", 
        "layoutRow": 1, 
        "color": "gray", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 13, 
        "channel": 1, 
        "layoutCol": 16
    }, 
    {
        "midi": 56, 
        "name": "SINE ", 
        "layoutRow": 1, 
        "color": "gray", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 14, 
        "channel": 1, 
        "layoutCol": 17
    }, 
    {
        "midi": 57, 
        "name": "A", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCA", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 15, 
        "channel": 1, 
        "layoutCol": 18
    }, 
    {
        "midi": 58, 
        "name": "D", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCA", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 16, 
        "channel": 1, 
        "layoutCol": 19
    }, 
    {
        "midi": 59, 
        "name": "S", 
        "layoutRow": 1, 
        "color": "black", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 17, 
        "channel": 1, 
        "layoutCol": 20
    }, 
    {
        "midi": 60, 
        "name": "R", 
        "layoutRow": 1, 
        "color": "yellow", 
        "section": "VCA", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 18, 
        "channel": 1, 
        "layoutCol": 21
    }, 
    {
        "midi": 61, 
        "name": "LEVEL", 
        "layoutRow": 1, 
        "color": "gray", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 19, 
        "channel": 1, 
        "layoutCol": 22
    }, 
    {
        "midi": 62, 
        "name": "INITIAL BRILLIANCE", 
        "layoutRow": 1, 
        "color": "green", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 20, 
        "channel": 1, 
        "layoutCol": 23
    }, 
    {
        "midi": 63, 
        "name": "INITIAL LEVEL", 
        "layoutRow": 1, 
        "color": "gray", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 21, 
        "channel": 1, 
        "layoutCol": 24
    }, 
    {
        "midi": 65, 
        "name": "AFTER BRILLIANCE", 
        "layoutRow": 1, 
        "color": "green", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 22, 
        "channel": 1, 
        "layoutCol": 25
    }, 
    {
        "midi": 66, 
        "name": "AFTER LEVEL", 
        "layoutRow": 1, 
        "color": "gray", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 23, 
        "channel": 1, 
        "layoutCol": 26
    }, 
    {
        "midi": 67, 
        "name": "SPEED", 
        "layoutRow": 2, 
        "color": "white", 
        "section": "VCO", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 24, 
        "channel": 2, 
        "layoutCol": 1
    }, 
    {
        "midi": 68, 
        "name": "PWM", 
        "layoutRow": 2, 
        "color": "green", 
        "section": "VCO", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 25, 
        "channel": 2, 
        "layoutCol": 2
    }, 
    {
        "midi": 69, 
        "name": "PW", 
        "layoutRow": 2, 
        "color": "green", 
        "section": "VCO", 
        "displayValueFuncName": "rangePW", 
        "type": "slider", 
        "byte": 26, 
        "channel": 2, 
        "layoutCol": 3
    }, 
    {
        "midi": 70, 
        "name": "SQUARE ON", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCO", 
        "displayValueFuncName": "rangeOnOff", 
        "type": "switchOffOn", 
        "byte": 76, 
        "channel": 2, 
        "layoutCol": 4
    }, 
    {
        "midi": 71, 
        "name": "SAW ON", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCO", 
        "displayValueFuncName": "rangeOnOff", 
        "type": "switchOffOn", 
        "byte": 75, 
        "channel": 2, 
        "layoutCol": 5
    }, 
    {
        "midi": 72, 
        "name": "NOISE", 
        "layoutRow": 2, 
        "color": "gray", 
        "section": "VCO", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 27, 
        "channel": 2, 
        "layoutCol": 6
    }, 
    {
        "midi": 73, 
        "name": "HPF", 
        "layoutRow": 2, 
        "color": "green", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 28, 
        "channel": 2, 
        "layoutCol": 7
    }, 
    {
        "midi": 119, 
        "name": "RESh", 
        "layoutRow": 2, 
        "color": "red", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 29, 
        "channel": 2, 
        "layoutCol": 8
    }, 
    {
        "midi": 75, 
        "name": "LPF", 
        "layoutRow": 2, 
        "color": "green", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 30, 
        "channel": 2, 
        "layoutCol": 9
    }, 
    {
        "midi": 76, 
        "name": "RESl", 
        "layoutRow": 2, 
        "color": "red", 
        "section": "VCF", 
        "displayValueFuncName": "rangeLowHigh", 
        "type": "slider", 
        "byte": 31, 
        "channel": 2, 
        "layoutCol": 10
    }, 
    {
        "midi": 77, 
        "name": "IL", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeIL", 
        "type": "slider", 
        "byte": 32, 
        "channel": 2, 
        "layoutCol": 11
    }, 
    {
        "midi": 78, 
        "name": "AL", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeAL", 
        "type": "slider", 
        "byte": 33, 
        "channel": 2, 
        "layoutCol": 12
    }, 
    {
        "midi": 79, 
        "name": "A", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 34, 
        "channel": 2, 
        "layoutCol": 13
    }, 
    {
        "midi": 80, 
        "name": "D", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCF", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 35, 
        "channel": 2, 
        "layoutCol": 14
    }, 
    {
        "midi": 81, 
        "name": "R", 
        "layoutRow": 2, 
        "color": "yellow", 
        "section": "VCF", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 36, 
        "channel": 2, 
        "layoutCol": 15
    }, 
    {
        "midi": 82, 
        "name": "VCF", 
        "layoutRow": 2, 
        "color": "gray", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 37, 
        "channel": 2, 
        "layoutCol": 16
    }, 
    {
        "midi": 83, 
        "name": "SINE ", 
        "layoutRow": 2, 
        "color": "gray", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 38, 
        "channel": 2, 
        "layoutCol": 17
    }, 
    {
        "midi": 84, 
        "name": "A", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCA", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 39, 
        "channel": 2, 
        "layoutCol": 18
    }, 
    {
        "midi": 85, 
        "name": "D", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCA", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 40, 
        "channel": 2, 
        "layoutCol": 19
    }, 
    {
        "midi": 86, 
        "name": "S", 
        "layoutRow": 2, 
        "color": "black", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 41, 
        "channel": 2, 
        "layoutCol": 20
    }, 
    {
        "midi": 87, 
        "name": "R", 
        "layoutRow": 2, 
        "color": "yellow", 
        "section": "VCA", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 42, 
        "channel": 2, 
        "layoutCol": 21
    }, 
    {
        "midi": 88, 
        "name": "LEVEL", 
        "layoutRow": 2, 
        "color": "gray", 
        "section": "VCA", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 43, 
        "channel": 2, 
        "layoutCol": 22
    }, 
    {
        "midi": 89, 
        "name": "INITIAL BRILLIANCE", 
        "layoutRow": 2, 
        "color": "green", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 44, 
        "channel": 2, 
        "layoutCol": 23
    }, 
    {
        "midi": 90, 
        "name": "INITIAL LEVEL", 
        "layoutRow": 2, 
        "color": "gray", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 45, 
        "channel": 2, 
        "layoutCol": 24
    }, 
    {
        "midi": 91, 
        "name": "AFTER BRILLIANCE", 
        "layoutRow": 2, 
        "color": "green", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 46, 
        "channel": 2, 
        "layoutCol": 25
    }, 
    {
        "midi": 92, 
        "name": "AFTER LEVEL", 
        "layoutRow": 2, 
        "color": "gray", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "range10", 
        "type": "slider", 
        "byte": 47, 
        "channel": 2, 
        "layoutCol": 26
    }, 
    {
        "midi": 93, 
        "name": "COARSE", 
        "layoutRow": 3, 
        "color": "black", 
        "section": "PITCH", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 77, 
        "channel": null, 
        "layoutCol": 1
    }, 
    {
        "midi": 94, 
        "name": "FINE", 
        "layoutRow": 3, 
        "color": "black", 
        "section": "PITCH", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 78, 
        "channel": null, 
        "layoutCol": 2
    }, 
    {
        "midi": 95, 
        "name": "DETUNE CH2", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "", 
        "displayValueFuncName": "rangeDetune", 
        "type": "slider", 
        "byte": 79, 
        "channel": null, 
        "layoutCol": 3
    }, 
    {
        "midi": 102, 
        "name": "FEET 1", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "FEET", 
        "displayValueFuncName": "rangeFeet", 
        "type": "slider", 
        "byte": 48, 
        "channel": 1, 
        "layoutCol": 4
    }, 
    {
        "midi": 103, 
        "name": "FEET 2", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "FEET", 
        "displayValueFuncName": "rangeFeet", 
        "type": "slider", 
        "byte": 49, 
        "channel": 2, 
        "layoutCol": 5
    }, 
    {
        "midi": 104, 
        "name": "FUNCTION", 
        "layoutRow": 3, 
        "color": "black", 
        "section": "SUB OSC", 
        "displayValueFuncName": "rangeFunction", 
        "type": "slider", 
        "byte": 50, 
        "channel": null, 
        "layoutCol": 6
    }, 
    {
        "midi": 105, 
        "name": "SPEED", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "SUB OSC", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 51, 
        "channel": null, 
        "layoutCol": 7
    }, 
    {
        "midi": 106, 
        "name": "VCO", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "SUB OSC", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 52, 
        "channel": null, 
        "layoutCol": 8
    }, 
    {
        "midi": 107, 
        "name": "VCF", 
        "layoutRow": 3, 
        "color": "green", 
        "section": "SUB OSC", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 53, 
        "channel": null, 
        "layoutCol": 9
    }, 
    {
        "midi": 108, 
        "name": "VCA", 
        "layoutRow": 3, 
        "color": "gray", 
        "section": "SUB OSC", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 54, 
        "channel": null, 
        "layoutCol": 10
    }, 
    {
        "midi": 8, 
        "name": "MIX", 
        "layoutRow": 3, 
        "color": "black", 
        "section": "", 
        "displayValueFuncName": "rangeMix", 
        "type": "slider", 
        "byte": 55, 
        "channel": null, 
        "layoutCol": 11
    }, 
    {
        "midi": 109, 
        "name": "BRILLIANCE", 
        "layoutRow": 3, 
        "color": "green", 
        "section": "", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 56, 
        "channel": null, 
        "layoutCol": 12
    }, 
    {
        "midi": 110, 
        "name": "RESSONANCE", 
        "layoutRow": 3, 
        "color": "red", 
        "section": "", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 57, 
        "channel": null, 
        "layoutCol": 13
    }, 
    {
        "midi": 111, 
        "name": "INITIAL", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 58, 
        "channel": null, 
        "layoutCol": 14
    }, 
    {
        "midi": 112, 
        "name": "SPEED", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 59, 
        "channel": null, 
        "layoutCol": 15
    }, 
    {
        "midi": 113, 
        "name": "VCO", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 60, 
        "channel": null, 
        "layoutCol": 16
    }, 
    {
        "midi": 114, 
        "name": "VCF", 
        "layoutRow": 3, 
        "color": "green", 
        "section": "TOUCH RESPONSE", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 61, 
        "channel": null, 
        "layoutCol": 17
    }, 
    {
        "midi": 115, 
        "name": "BRILLIANCE LOW", 
        "layoutRow": 3, 
        "color": "green", 
        "section": "KEYBOARD", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 62, 
        "channel": null, 
        "layoutCol": 18
    }, 
    {
        "midi": 116, 
        "name": "BRILLIANCE HIGH", 
        "layoutRow": 3, 
        "color": "green", 
        "section": "KEYBOARD", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 63, 
        "channel": null, 
        "layoutCol": 19
    }, 
    {
        "midi": 117, 
        "name": "LEVEL LOW", 
        "layoutRow": 3, 
        "color": "gray", 
        "section": "KEYBOARD", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 64, 
        "channel": null, 
        "layoutCol": 20
    }, 
    {
        "midi": 118, 
        "name": "LEVEL HIGH", 
        "layoutRow": 3, 
        "color": "gray", 
        "section": "KEYBOARD", 
        "displayValueFuncName": "rangeNone", 
        "type": "slider", 
        "byte": 65, 
        "channel": null, 
        "layoutCol": 21
    }, 
    {
        "midi": 5, 
        "name": "GLIDE TIME", 
        "layoutRow": 3, 
        "color": "white", 
        "section": "", 
        "displayValueFuncName": "rangeShortLong", 
        "type": "slider", 
        "byte": 66, 
        "channel": null, 
        "layoutCol": 22
    }, 
    {
        "midi": 120, 
        "name": "GLIDE MODE", 
        "layoutRow": 3, 
        "color": "black", 
        "section": "", 
        "displayValueFuncName": "rangeGlideMode", 
        "type": "glideMode", 
        "byte": -1, 
        "channel": null, 
        "layoutCol": 23
    }
];
